id: cb5282c69ad24b52b1a6fd72d7bad32f
initial_creation_type: ocr
source_metadata:
  volumes:
    fed7a309eee84a468df127b9c66a6f9b:
      base_file: v115.txt
      image_group_id: I1PD95961
      title: ''
      total_pages: 1880
      volume_number: 116
